apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exercise1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exercise1
  template:
    metadata:
      labels:
        app: exercise1
    spec:
      containers:
      - name: exercise1
        image: f5devcentral/f5-demo-httpd:nginx
        ports:
        - containerPort: 80