apiVersion: v1
kind: Service
metadata:
   name: exercise3-svc
   labels:
     cis.f5.com/as3-tenant: AS3
     cis.f5.com/as3-app: ExApp3
     cis.f5.com/as3-pool: ingress_pool
spec:
   type: NodePort
   ports:
   - port: 80
     targetPort: 8080
     protocol: TCP
     name: http
   selector:
     app: exercise3