---
kind: ConfigMap
apiVersion: v1
metadata:
  name: exercise3-as3-configmap
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.1.0",
        "id": "example3",
        "label": "CIS AS3 Example",
        "remark": "Example of using CIS",
        "AS3": {
          "class": "Tenant",
          "ExApp3": {
            "class": "Application",
            "template": "generic",
            "ingress": {
                "class": "Service_TCP",
                "virtualAddresses": ["10.1.10.10"],
              "remark":"ingress: f5demo.tcp.v1",

              "virtualPort": 80,
                "pool": "ingress_pool"
            },
            "ingress_pool": {
                "class": "Pool",
                "monitors": [ "tcp" ],
                "members": [{
                  "servicePort": 80,
                  "serverAddresses": []
                }]
            }
      }
      }
    }
    }