---
kind: ConfigMap
apiVersion: v1
metadata:
  name: exercise3-as3-configmap
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.1.0",
        "id": "example3",
        "label": "CIS AS3 Example",
        "remark": "Example of using CIS",
       "Common": {
          "class": "Tenant",
          "Shared": {
            "class": "Application",
            "template": "shared",
            "XFF_HTTP_Profile": {
              "class": "HTTP_Profile",
                "xForwardedFor": true
               }
       }
       },
        "AS3": {
          "class": "Tenant",
          "ExApp3": {
             "class": "Application",
             "template": "generic",
             "ingress": {
                "class": "Service_HTTP",
                "virtualAddresses": ["10.1.10.10"],

               "virtualPort": 80,
               "remark":"ingress: f5demo.waf.http.v1",
               "pool": "ingress_pool",
               "profileHTTP":{"use": "/Common/Shared/XFF_HTTP_Profile"},
               "policyWAF":{"bigip":"/Common/linux-high"},
               "securityLogProfiles": [
               {
                 "bigip": "/Common/Log all requests"
               }
               ]
             },
             "ingress_pool": {
                "class": "Pool",
                "monitors": [
                   "http"
                ],
                "members": [{
                   "servicePort": 80,
                   "serverAddresses": [
                   ]
                }]
             }
       }
       }
    }
    }