apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exercise3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exercise3
  template:
    metadata:
      labels:
        app: exercise3
    spec:
      containers:
      - name: exercise3
        image: f5devcentral/f5-hello-world
        ports:
        - containerPort: 80