---
kind: ConfigMap
apiVersion: v1
metadata:
  name: example-vs-2
  namespace: default
data:
  template: |
    {
      "declaration": {
        "kubernetes_AS3": {
          "Shared": {
            "ingress_10_1_10_80_443": {
              "virtualAddresses": [
                "10.1.10.81"
              ]
            }
          }
        }
      }
    }
